# Generated by Django 2.1.4 on 2020-04-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200409_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
